"use client";

import { useState, type FormEvent } from "react";
import { Alert } from "@/components/ui/Alert";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardTitle } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";

type RecordItem = { id: string; resultStatus: string; completedAt: string | null; remarks: string | null; appointmentDate: string | null };
type ResultData = { studentNumber: string; studentName: string; collegeName: string; programName: string; examResults: RecordItem[]; laboratoryResults: RecordItem[]; appointments: Array<{ id: string; scheduleType: string; appointmentDate: string; status: string }> };

export function ResultsWorkspace() {
  const [studentNumber, setStudentNumber] = useState(""); const [data, setData] = useState<ResultData>(); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  async function load(value = studentNumber) { setPending(true); setError(undefined); const response = await fetch(`/api/results?studentNumber=${encodeURIComponent(value)}`); const payload = await response.json(); if (!response.ok) { setData(undefined); setError(payload.error?.message); } else setData(payload.data); setPending(false); }
  function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void load(); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!data) return; const form = new FormData(event.currentTarget); const resultType = String(form.get("resultType")); const status = String(form.get("resultStatus")); const response = await fetch("/api/results", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ studentNumber: data.studentNumber, appointmentId: form.get("appointmentId"), resultType, resultStatus: status, completedAt: form.get("completedAt"), remarks: form.get("remarks") }) }); const payload = await response.json(); if (!response.ok) setError(payload.error?.message); else { event.currentTarget.reset(); await load(data.studentNumber); } }
  return <div className="grid gap-6"><Card><form onSubmit={search} className="flex flex-col gap-3 sm:flex-row"><Input value={studentNumber} onChange={(event) => setStudentNumber(event.target.value)} placeholder="Student number" required /><Button type="submit" disabled={pending}>{pending ? "Searching..." : "Retrieve records"}</Button></form></Card>{error ? <Alert tone="danger">{error}</Alert> : null}{data ? <><Card><h2 className="text-xl font-bold text-ink">{data.studentName}</h2><p className="text-sm text-muted">{data.studentNumber} · {data.programName}</p></Card><Card><CardTitle>Encode result</CardTitle><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-2"><Select name="resultType" required><option value="PHYSICAL_EXAM">Physical examination</option><option value="LABORATORY">Laboratory</option></Select><Select name="appointmentId"><option value="">Historical record without appointment</option>{data.appointments.map((appointment) => <option key={appointment.id} value={appointment.id}>{appointment.scheduleType.replaceAll("_", " ")} · {appointment.appointmentDate}</option>)}</Select><Select name="resultStatus" required><option value="PENDING_UPLOAD">Pending upload</option><option value="COMPLETED">Completed</option><option value="REQUIRES_FOLLOW_UP">Requires follow-up</option><option value="NOT_APPLICABLE">Not applicable</option></Select><Input name="completedAt" type="date" /><Textarea name="remarks" placeholder="Remarks" className="md:col-span-2" /><Button type="submit" className="md:justify-self-start">Save result</Button></form></Card><div className="grid gap-6 xl:grid-cols-2"><HistoryCard title="Physical examination history" items={data.examResults} /><HistoryCard title="Laboratory history" items={data.laboratoryResults} /></div></> : null}</div>;
}

function HistoryCard({ title, items }: { title: string; items: RecordItem[] }) { return <Card><CardTitle>{title}</CardTitle><div className="mt-4 grid gap-3">{items.map((item) => <div key={item.id} className="rounded-xl border border-cpu-navy/8 bg-cpu-navy-soft/55 p-4"><div className="flex justify-between gap-3"><p className="font-bold text-ink">{item.completedAt ?? item.appointmentDate ?? "No date"}</p><Badge tone={item.resultStatus === "COMPLETED" ? "success" : item.resultStatus === "REQUIRES_FOLLOW_UP" ? "warning" : "neutral"}>{item.resultStatus}</Badge></div>{item.remarks ? <p className="mt-2 text-sm text-muted">{item.remarks}</p> : null}</div>)}{items.length === 0 ? <p className="text-sm text-muted">No previous records.</p> : null}</div></Card>; }
